<a href="https://colab.research.google.com/github/BettyMinik/Curso-de-introduccion-a-Big-Data-Parte-2-nov2021/blob/main/Ejercicios_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Crear un array con valores dentro del rango 10 a 49

In [3]:
import numpy as np
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

2. Invertir el array

In [23]:
b=np.flip(a)
a[::-1]
#b

array([7, 6, 5, 4, 3, 2, 1, 0])

3. Crear una array o matriz 1D con valores de 0 a 8. Cambiar la forma de la matriz a 3x3

In [24]:
a=np.arange(0,9)
a
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Crear una matriz identidad de 6x6

In [17]:
identidad = np.eye(6)
identidad

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

5. Crear una matriz con valores al azar con forma 3x3x3 

In [18]:
a=np.random.rand(3,3,3)
a

array([[[0.04479738, 0.02237863, 0.78734905],
        [0.65333117, 0.60412899, 0.06244475],
        [0.44459791, 0.44008054, 0.25007734]],

       [[0.11674962, 0.93944062, 0.95918147],
        [0.92947042, 0.1142009 , 0.19601007],
        [0.75542177, 0.12726233, 0.57667888]],

       [[0.80710373, 0.33410191, 0.4899404 ],
        [0.434987  , 0.80844644, 0.43508968],
        [0.05427264, 0.22718259, 0.77119181]]])

6. Encontrar los indices de los valores minimos y maximos de la anterior matriz

7. Crear dos arrays al azar A y B, verificar si son iguales

8. Encontrar los indices que no son ceros del array [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

9. Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

10. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4